site_name: OpenVoiceChat Docs
nav:
  - Home: index.html
  - Docs: docs.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quickstart: getting-started/quickstart.md
  - API Reference:
    - Base Classes: base_classes.md
    - STT Classes: stt_classes.md
    - STT utils: stt_utils.md
    - TTS Classes: tts_classes.md
    - LLM Classes: llm_classes.md
    - Utils: utils.md
  - Custom Models: Adding_models.md
theme:
    name: 'material'
    palette:
      scheme: slate
      primary: deep orange
    logo: main_logo_no_text.png
    favicon: main_logo_no_text.png
    features:
      - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        import:
        - https://docs.python.org/3/objects.inv
        paths: [openvoicechat]
        options:
          filters: []
          members_order: source
          allow_inspection: true
          docstring_style: sphinx
          docstring_section_style: table
          heading_level: 2
          merge_init_into_class: true
          separate_signature: true
          show_root_heading: true
          show_docstring_description: true
          show_docstring_attributes: false
          show_root_full_path: true
          show_signature_annotations: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          show_if_no_docstring: true
          show_source: true
          summary: true